from __future__ import annotations

"""Stage X (2026-05-06) — drawer-native folder summary.

Drawer-mode rewrite of the legacy ``brain/folder_gist.py``
(record/LayoutPolicy-based). Walks the folder tree and writes
``_summary.md`` containing:

- drawer count
- hot drawers (drawers with sections whose memory_zone=hot)
- routing signposts (drawer count per sub-folder)
- AI traversal hint

Principles:
- D2 decision — DB only writes stats. If AI replaces it by hand, mark with
  ``_authored_by: ai`` and protect it (consistent with
  drawer_summary.write_summary).
- Files with _authored_by: ai are *not touched* during refresh.
"""

from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

from mddbai.brain.drawer_summary import (
    AUTHORED_BY_AI,
    AUTHORED_BY_KEY,
    AUTHORED_BY_STATS,
    SUMMARY_NAME,
)
from mddbai.codec.frontmatter import parse as fm_parse, render as fm_render
from mddbai.codec.section_meta import parse_sections_meta
from mddbai.storage.transactional import transactional_rmw

if TYPE_CHECKING:
    from mddbai.engine import Database


_SYSTEM_DIR_NAMES = frozenset({
    "_palace",
    "_drawers",
    "_user_lexicon",
    "_inbox",
    "_clusters",
    "_homeostasis",
    "_wal",
    "_registry",
})


@dataclass
class FolderSummary:
    """Summary statistics for a single folder."""

    table: str
    rel: str  # Path relative to table. Empty string means the table root.
    drawer_count: int = 0
    hot_drawers: list[str] = field(default_factory=list)
    sub_folders: dict[str, int] = field(default_factory=dict)
    sample_drawers: list[str] = field(default_factory=list)

    def folder_label(self) -> str:
        return self.rel or self.table

    def to_md(self) -> str:
        meta: dict[str, Any] = {
            "_kind": "folder_summary",
            AUTHORED_BY_KEY: AUTHORED_BY_STATS,
            "table": self.table,
            "rel": self.rel,
            "drawer_count": self.drawer_count,
        }
        body_lines = [
            f"# Folder: {self.folder_label()}",
            "",
            f"drawers: {self.drawer_count}",
        ]
        if self.hot_drawers:
            body_lines.append("")
            body_lines.append("## Hot drawers (memory_zone=hot)")
            body_lines.append("")
            for d in self.hot_drawers:
                body_lines.append(f"- `{d}`")
        if self.sub_folders:
            body_lines.append("")
            body_lines.append("## Sub-folders (signposts)")
            body_lines.append("")
            for name, count in sorted(self.sub_folders.items()):
                body_lines.append(f"- `{name}/` ({count} drawers)")
        if self.sample_drawers:
            body_lines.append("")
            body_lines.append("## Sample drawers")
            body_lines.append("")
            for d in self.sample_drawers:
                body_lines.append(f"- `{d}`")
        body_lines.append("")
        body_lines.append(
            "_(stats auto-generated by mddbai. AI-authored summaries are protected.)_"
        )
        return fm_render(meta, "\n".join(body_lines) + "\n")


def _is_drawer_file(path: Path) -> bool:
    if not path.is_file():
        return False
    if not path.name.endswith(".md"):
        return False
    if path.name == SUMMARY_NAME or path.name.startswith("_"):
        return False
    if path.name.endswith(".lock") or path.name.endswith(".tmp"):
        return False
    return True


def _hot_drawers_in_folder(folder: Path) -> list[str]:
    """Drawers (recursively) inside the folder that have at least one hot section."""

    out: list[str] = []
    for path in folder.rglob("*.md"):
        if not _is_drawer_file(path):
            continue
        rel_parts = path.relative_to(folder).parts
        if any(part.startswith("_") for part in rel_parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
            meta, _ = fm_parse(text)
        except (OSError, ValueError):
            continue
        try:
            sections_meta = parse_sections_meta(meta)
        except Exception:  # noqa: BLE001
            continue
        if any(sm.memory_zone == "hot" for sm in sections_meta.values()):
            rel = path.relative_to(folder).as_posix()
            if rel.endswith(".md"):
                rel = rel[:-3]
            out.append(rel)
    return sorted(out)


def build_folder_summary(
    table_root: Path, folder: Path, *, table: str, sample_size: int = 5
) -> FolderSummary:
    """Compute statistics for a single folder in one pass."""

    rel = "" if folder == table_root else folder.relative_to(table_root).as_posix()
    summary = FolderSummary(table=table, rel=rel)

    drawer_paths: list[Path] = []
    sub_counts: dict[str, int] = {}

    for entry in folder.iterdir():
        if entry.is_dir():
            if entry.name.startswith("_"):
                continue
            count = sum(1 for p in entry.rglob("*.md") if _is_drawer_file(p))
            if count:
                sub_counts[entry.name] = count
        elif entry.is_file() and _is_drawer_file(entry):
            drawer_paths.append(entry)

    direct_count = len(drawer_paths)
    nested_count = sum(sub_counts.values())
    summary.drawer_count = direct_count + nested_count
    summary.sub_folders = sub_counts

    summary.sample_drawers = sorted(p.stem for p in drawer_paths)[:sample_size]
    summary.hot_drawers = _hot_drawers_in_folder(folder)
    return summary


def iter_table_folders(table_root: Path) -> Iterable[Path]:
    """Walk the table root (inclusive) and yield only folders that contain
    drawers directly or recursively."""

    if not table_root.exists():
        return
    yield table_root
    for entry in table_root.rglob("*"):
        if not entry.is_dir():
            continue
        if any(part.startswith("_") for part in entry.relative_to(table_root).parts):
            continue
        # Skip folders with no drawers at all (avoid orphan summaries)
        has_drawer = False
        for p in entry.rglob("*.md"):
            if _is_drawer_file(p):
                has_drawer = True
                break
        if has_drawer:
            yield entry


def refresh_folder_summary(
    db: Database, summary: FolderSummary, *, overwrite_ai: bool = False
) -> Path | None:
    """Atomically refresh a single ``_summary.md`` file.

    With ``overwrite_ai=False`` (default), files marked
    ``_authored_by: ai`` are preserved.

    Returns:
        The path written. None if skipped due to AI-authored protection.
    """

    folder = db.config.data_dir / summary.table
    if summary.rel:
        folder = folder / summary.rel
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / SUMMARY_NAME
    new_text = summary.to_md()
    skipped = [False]

    def _mutator(text: str) -> str:
        if not overwrite_ai and text:
            try:
                meta, _ = fm_parse(text)
            except ValueError:
                meta = {}
            if str(meta.get(AUTHORED_BY_KEY, "")) == AUTHORED_BY_AI:
                skipped[0] = True
                return text
        return new_text

    transactional_rmw(path, _mutator, fsync=False)
    return None if skipped[0] else path


def refresh_table_summaries(
    db: Database, table: str, *, overwrite_ai: bool = False, sample_size: int = 5
) -> list[Path]:
    """Auto-refresh _summary.md for every folder in the table.

    Returns:
        Paths of _summary.md files actually written (excluding ones
        skipped because they were AI-authored).
    """

    table_root = db.config.data_dir / table
    if not table_root.exists():
        return []
    written: list[Path] = []
    for folder in iter_table_folders(table_root):
        summary = build_folder_summary(
            table_root, folder, table=table, sample_size=sample_size
        )
        if summary.drawer_count == 0:
            continue
        result = refresh_folder_summary(
            db, summary, overwrite_ai=overwrite_ai
        )
        if result is not None:
            written.append(result)
    return written


__all__ = [
    "FolderSummary",
    "build_folder_summary",
    "iter_table_folders",
    "refresh_folder_summary",
    "refresh_table_summaries",
]
